### PR TITLE
Register GHRepositorySearchBuilder$RepositorySearchResult and GHIssueSearchBuilder$IssueSearchResult for reflection

### PR DESCRIPTION
**Pull request by aheritier**
Required for gitHub.searchRepositories() and gitHub.searchIssues()

I had to use RegisterForReflection

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks for the PR but the bug is different. All the classes extending `SearchResult` should already be registered but I don't know how it missed it... the wrong class has been imported :/

I'll go fix that. Thanks anyway, this bug has been there since forever!

**Comment by gsmet** [comment]
Correct fix is here: https://github.com/quarkiverse/quarkus-github-api/pull/136 . The class was package protected and things got messy.
I will release once CI is green.

**Comment by gsmet** [comment]
@aheritier [1.303.2](https://repo1.maven.org/maven2/io/quarkiverse/githubapi/quarkus-github-api/1.303.2/) has hit Central and should fix your issue!

**Comment by aheritier** [comment]
ok I better understand.
I confirm that your fix is working
Thanks a lot @gsmet

**Pull request closed without merging**
